---
collections: 
  - cisco.asa
  - cisco.ios
  - cisco.iosxr
  - cisco.meraki
  - cisco.mso
  - cisco.nso
  - cisco.nxos
  - cisco.ucs
  - community.general
  - community.hashi_vault
  - community.vmware
  - community.windows
