---

- name: cisco_sh_ver
  hosts: all
  gather_facts: false
  ask_variables_on_launch=true
 
  

  tasks:
    - name: Create VLAN
      cisco.ios.ios_vlans:
        config:
        - name: "{{ vlan_name }}"
          vlan_id: "{{ vlan_id }}"
          state: active
