----

- name: cisco_sh_ver
  hosts: all
  gather_facts: false 
  

  tasks:

    - name: run multiple commands and evaluate the output
       cisco.ios.ios_command:
        commands:
          - configure terminal
          - interface gigabitEthernet 1/0/10
          - shutdown
