---

- name: cisco_sh_ver
  hosts: all
  gather_facts: false
 
  

  tasks:
  
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
       config:
       - name: FastEthernet1/1
        ipv4:
       - address: 192.168.0.1/24
        secondary: true
    state: merged
