---

- name: configure IOS XE devices using NETCONF
  hosts: all
  gather_facts: no

  tasks:
  - name: set Management interface description
    netconf_config:
      xml: |
        <config>
          <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
            <interface>
              <name>GigabitEthernet1/0/10</name>
              <description>Managed by Ansible using netconf connection</description>
            </interface>
          </interfaces>
        </config>
