---

- name: cisco_sh_ver
  hosts: all
  gather_facts: true
 
  

  tasks:
    - name: Gather only the interfaces resource facts and no legacy facts
      cisco.ios.ios_facts:
        gather_subset:
         - '!all'
         - '!min'
        gather_network_resources:
         - interfaces

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
        - name: GigabitEthernet1/0/10
          description: Configured and Merged by Ansible Network
          enabled: false
        state: merged
