---

- name: cisco_sh_ver
  hosts: all
  gather_facts: false
 
  

  tasks:
  
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
        - name: GigabitEthernet1/0/10
          enabled: false
          # description: Configured and Merged by Ansible Network
        state: replaced
