---
- name: cisco_sh_ver
  hosts: all
  gather_facts: false 
  
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version
        register: result

      - name: Display result to terminal window
        debug:
          var: result.stdout_lines
      
