---

- name: cisco_sh_ver
  hosts: all
  gather_facts: false 
  
  tasks:
    - name: run show version on the routers
      cisco.ios.ios_command:
        commands: show interfaces status
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
