- name: cisco_sh_ver
  hosts: all
  gather_facts: false 
  connection: ansible.netcommon.network_cli
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands: show version       
  - name: show run on remote devices
    become: true
    cisco.ios.ios_command:
     commands: 
     - show run
