---

- name: cisco_test
  hosts: all
  gather_facts: false
  
  tasks:
  
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
        - name: GigabitEthernet1/0/10
          enabled: 'no'
          # description: Configured and Merged by Ansible Network
        state: merged
      register: ios_interface_output

    - name: "TASK 2: SYS >> DEBUG OUTPUT"
      debug:
        msg: "{{ ios_interface_output }}"
